import React from 'react';
import MetricCard from '../components/MetricCard';
import RiskBadge from '../components/RiskBadge';
import StudentTable from '../components/StudentTable';
import { formatPercent } from '../utils/data';

export default function Dashboard({ students, onSelect, setPage }) {
  const highDropout = students.filter((s) => s.risks.dropout === 'High');
  const highAcademic = students.filter((s) => s.risks.academic === 'High');
  const average = students.length ? students.reduce((sum, s) => sum + Number(s.engagement.assignment_completion_rate || 0), 0) / students.length : 0;
  return <section className="page"><div className="page-heading"><div><p className="eyebrow">Monday, 5 October 2026</p><h1>Good morning, Jane</h1><p>District overview of schools, grades, attendance, and model-predicted risk.</p></div><span className="data-label">District workspace</span></div><div className="metrics four"><MetricCard label="Students" value={students.length} detail="students in the district" /><MetricCard label="High academic risk" value={highAcademic.length} detail="model prediction" tone="warning" /><MetricCard label="High dropout risk" value={highDropout.length} detail="model prediction" tone="danger" /><MetricCard label="Avg. assignment completion" value={formatPercent(average)} detail="across this district" /></div><div className="dashboard-grid"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">Needs attention</p><h2>Priority students</h2></div><button className="text-button" onClick={() => setPage('dropout')}>View dropout risk →</button></div><StudentTable students={highDropout.slice(0, 6)} onSelect={onSelect} compact /></div><div className="panel summary-panel"><p className="eyebrow">Risk snapshot</p><h2>District signals</h2><div className="risk-group"><h3>Academic risk</h3><div className="signal"><span><RiskBadge value="High" /> High</span><strong>{students.filter((s) => s.risks.academic === 'High').length}</strong></div><div className="signal"><span><RiskBadge value="Medium" /> Medium</span><strong>{students.filter((s) => s.risks.academic === 'Medium').length}</strong></div><div className="signal"><span><RiskBadge value="Low" /> Low</span><strong>{students.filter((s) => s.risks.academic === 'Low').length}</strong></div></div><div className="risk-group"><h3>Dropout risk</h3><div className="signal"><span><RiskBadge value="High" /> High</span><strong>{students.filter((s) => s.risks.dropout === 'High').length}</strong></div><div className="signal"><span><RiskBadge value="Medium" /> Medium</span><strong>{students.filter((s) => s.risks.dropout === 'Medium').length}</strong></div><div className="signal"><span><RiskBadge value="Low" /> Low</span><strong>{students.filter((s) => s.risks.dropout === 'Low').length}</strong></div></div></div></div></section>;
}
