import React from 'react';
import { formatPercent } from '../utils/data';
import RiskBadge from '../components/RiskBadge';
import MetricCard from '../components/MetricCard';

export default function StudentProfile({ student, factors, onBack }) {
  return <section className="page"><button className="back-link" onClick={onBack}>← Back to students</button><div className="profile-title"><div><p className="eyebrow">Student profile</p><h1>{student.student_id}</h1><p>{student.gender} · Grade {student.grade} · {student.school_id}</p></div><div className="profile-risks"><span>Academic <RiskBadge value={student.risks.academic} /></span><span>Dropout <RiskBadge value={student.risks.dropout} /></span></div></div>
    <div className="metrics four"><MetricCard label="Attendance" value={formatPercent(student.attendance.attendance_rate)} detail={`${student.attendance.days_absent || '—'} days absent`} /><MetricCard label="Assignment completion" value={formatPercent(student.engagement.assignment_completion_rate)} detail={`${student.engagement.completed_assignments || '—'} completed`} /></div>
    <div className="profile-grid"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">Assignments</p><h2>Learning activity</h2></div></div><div className="assignment-row"><div><span>Completed assignments</span><strong>{student.engagement.completed_assignments || '—'}</strong></div><div><span>Missed assignments</span><strong>{student.engagement.missed_assignments || '—'}</strong></div><div><span>Completion rate</span><strong>{formatPercent(student.engagement.assignment_completion_rate)}</strong></div></div><div className="progress"><span style={{ width: `${student.engagement.assignment_completion_rate || 0}%` }} /></div></div><div className="panel"><div className="panel-heading"><div><p className="eyebrow">Academic record</p><h2>Recent performance</h2></div></div><dl className="details"><div><dt>Previous exam</dt><dd>{formatPercent(student.academic.previous_exam_score)}</dd></div><div><dt>Recent exam</dt><dd>{formatPercent(student.academic.recent_exam_score)}</dd></div><div><dt>Performance change</dt><dd>{student.academic.performance_change || '—'}</dd></div><div><dt>Failed subjects</dt><dd>{student.academic.previous_failed_subjects || '—'}</dd></div></dl></div></div>
    <div className="panel recent-data"><div className="panel-heading"><div><p className="eyebrow">Latest records</p><h2>Recent results</h2></div></div><div className="assignment-row"><div><span>Recent exam</span><strong>{formatPercent(student.academic.recent_exam_score)}</strong></div><div><span>Quiz average</span><strong>{formatPercent(student.academic.quiz_average)}</strong></div><div><span>Assignment average</span><strong>{formatPercent(student.academic.assignment_average)}</strong></div></div></div>
  </section>;
}
